# Generated by Django 3.2.7 on 2021-09-25 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebPage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('price', models.DecimalField(decimal_places=4, max_digits=1000)),
                ('description', models.TextField()),
            ],
        ),
    ]
