# Generated by Django 3.2.7 on 2021-09-25 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebPage', '0004_alter_product_like'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=4, default=0.0, max_digits=1000),
        ),
    ]
