# Generated by Django 3.2.7 on 2021-09-25 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebPage', '0005_alter_product_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='Like',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=4, max_digits=1000),
        ),
    ]
