# Generated by Django 3.2.7 on 2021-09-25 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebPage', '0007_alter_product_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('First_Name', models.CharField(max_length=500)),
                ('Second_Name', models.CharField(max_length=500)),
                ('Gender', models.CharField(max_length=500)),
                ('dob', models.DateField()),
                ('Class', models.CharField(max_length=500)),
                ('Stream', models.CharField(max_length=500)),
                ('EmailID', models.EmailField(max_length=254)),
                ('Section', models.CharField(max_length=500)),
                ('Parent_Name', models.CharField(max_length=500)),
                ('Parent_Contact', models.CharField(max_length=500)),
                ('Address', models.CharField(max_length=500)),
            ],
        ),
    ]
