# Generated by Django 3.2.7 on 2021-09-25 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebPage', '0008_student'),
    ]

    operations = [
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('staff_id', models.CharField(max_length=500)),
                ('staff_name', models.CharField(max_length=500)),
                ('gender', models.CharField(max_length=500)),
                ('doj', models.DateField()),
                ('designation', models.CharField(max_length=500)),
            ],
        ),
    ]
