# Generated by Django 3.2.7 on 2021-09-25 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebPage', '0009_staff'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='address',
            field=models.CharField(default='hey', max_length=500),
        ),
        migrations.AddField(
            model_name='staff',
            name='class_heading',
            field=models.CharField(default='h', max_length=500),
        ),
        migrations.AddField(
            model_name='staff',
            name='emailid',
            field=models.EmailField(default='hey', max_length=254),
        ),
        migrations.AddField(
            model_name='staff',
            name='mobile_no',
            field=models.CharField(default='hey', max_length=500),
        ),
        migrations.AddField(
            model_name='staff',
            name='qualification',
            field=models.CharField(default='hey', max_length=500),
        ),
        migrations.AlterField(
            model_name='staff',
            name='designation',
            field=models.CharField(default='hey', max_length=500),
        ),
        migrations.AlterField(
            model_name='staff',
            name='doj',
            field=models.DateField(default='hey@gmail.com'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='gender',
            field=models.CharField(default='hey', max_length=500),
        ),
        migrations.AlterField(
            model_name='staff',
            name='staff_id',
            field=models.CharField(default='hey', max_length=500),
        ),
        migrations.AlterField(
            model_name='staff',
            name='staff_name',
            field=models.CharField(default='hey', max_length=500),
        ),
    ]
