# Generated by Django 3.2.7 on 2021-09-25 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebPage', '0010_auto_20210925_2316'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='address',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='staff',
            name='class_heading',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='staff',
            name='designation',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='staff',
            name='doj',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='staff',
            name='emailid',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='staff',
            name='gender',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='staff',
            name='mobile_no',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='staff',
            name='qualification',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='staff',
            name='staff_id',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='staff',
            name='staff_name',
            field=models.CharField(max_length=500),
        ),
    ]
