# Generated by Django 3.2.7 on 2021-09-26 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebPage', '0012_student_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='C:/Users/gilbert/Desktop/Admin/PYTHON/Tutorials & Projects\\Django/Projects/Practices/Website/images/'),
        ),
    ]
