# Generated by Django 3.2.7 on 2021-09-26 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebPage', '0014_alter_student_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='dob',
            field=models.DateField(default='12/12/2000'),
        ),
    ]
