# Generated by Django 3.2.7 on 2021-09-26 20:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebPage', '0019_alter_student_dob'),
    ]

    operations = [
        migrations.CreateModel(
            name='Postings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('body', models.TextField()),
                ('date_posted', models.DateField(default=datetime.datetime(2021, 9, 26, 22, 35, 42, 162426))),
            ],
        ),
        migrations.AlterField(
            model_name='student',
            name='dob',
            field=models.DateField(default=datetime.datetime(2021, 9, 26, 22, 35, 42, 160421)),
        ),
    ]
