# Generated by Django 3.2.7 on 2021-09-26 20:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebPage', '0020_auto_20210926_2235'),
    ]

    operations = [
        migrations.CreateModel(
            name='Posting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('body', models.TextField()),
                ('date_posted', models.DateField(default=datetime.datetime(2021, 9, 26, 22, 38, 24, 579978))),
            ],
        ),
        migrations.DeleteModel(
            name='Postings',
        ),
        migrations.AlterField(
            model_name='student',
            name='dob',
            field=models.DateField(default=datetime.datetime(2021, 9, 26, 22, 38, 24, 577973)),
        ),
    ]
