# Generated by Django 3.2.7 on 2021-09-26 20:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebPage', '0021_auto_20210926_2238'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posting',
            name='date_posted',
            field=models.DateField(default=datetime.datetime(2021, 9, 26, 22, 39, 23, 884544)),
        ),
        migrations.AlterField(
            model_name='student',
            name='dob',
            field=models.DateField(default=datetime.datetime(2021, 9, 26, 22, 39, 23, 882539)),
        ),
    ]
