# Generated by Django 3.2.7 on 2021-09-26 21:18

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('WebPage', '0025_auto_20210926_2306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='date_posted',
            field=models.DateField(default=datetime.datetime(2021, 9, 26, 23, 18, 49, 405290)),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/announcements'),
        ),
        migrations.AlterField(
            model_name='posting',
            name='date_posted',
            field=models.DateField(default=datetime.datetime(2021, 9, 26, 23, 18, 49, 404287)),
        ),
        migrations.AlterField(
            model_name='posting',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/Postings'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to='images/profiles/'),
        ),
        migrations.AlterField(
            model_name='student',
            name='dob',
            field=models.DateField(default=datetime.datetime(2021, 9, 26, 23, 18, 49, 401247)),
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Class', models.CharField(max_length=500)),
                ('Subject', models.CharField(max_length=500)),
                ('Topic', models.CharField(max_length=500)),
                ('Sub_Topic', models.CharField(max_length=500)),
                ('Question', models.TextField()),
                ('Answer', models.CharField(max_length=1000)),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/Questions')),
                ('date_posted', models.DateField(default=datetime.datetime(2021, 9, 26, 23, 18, 49, 405290))),
                ('Q_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
