# Generated by Django 3.2.7 on 2021-09-26 21:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebPage', '0026_auto_20210926_2318'),
    ]

    operations = [
        migrations.CreateModel(
            name='New',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Category', models.CharField(max_length=500)),
                ('Title', models.CharField(max_length=500)),
                ('img', models.ImageField(blank=True, null=True, upload_to='images/News')),
                ('news_content', models.TextField()),
                ('date_posted', models.DateField(default=datetime.datetime(2021, 9, 26, 23, 26, 17, 273392))),
            ],
        ),
        migrations.AlterField(
            model_name='announcement',
            name='date_posted',
            field=models.DateField(default=datetime.datetime(2021, 9, 26, 23, 26, 17, 271386)),
        ),
        migrations.AlterField(
            model_name='posting',
            name='date_posted',
            field=models.DateField(default=datetime.datetime(2021, 9, 26, 23, 26, 17, 270384)),
        ),
        migrations.AlterField(
            model_name='question',
            name='date_posted',
            field=models.DateField(default=datetime.datetime(2021, 9, 26, 23, 26, 17, 272389)),
        ),
        migrations.AlterField(
            model_name='student',
            name='dob',
            field=models.DateField(default=datetime.datetime(2021, 9, 26, 23, 26, 17, 268379)),
        ),
    ]
