# Generated by Django 3.2.7 on 2021-09-27 13:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebPage', '0035_auto_20210927_1441'),
    ]

    operations = [
        migrations.RenameField(
            model_name='posting',
            old_name='P_user',
            new_name='author',
        ),
        migrations.AlterField(
            model_name='announcement',
            name='date_posted',
            field=models.DateField(default=datetime.datetime(2021, 9, 27, 15, 3, 48, 917824)),
        ),
        migrations.AlterField(
            model_name='new',
            name='date_posted',
            field=models.DateField(default=datetime.datetime(2021, 9, 27, 15, 3, 48, 919829)),
        ),
        migrations.AlterField(
            model_name='posting',
            name='date_posted',
            field=models.DateField(default=datetime.datetime(2021, 9, 27, 15, 3, 48, 916822)),
        ),
        migrations.AlterField(
            model_name='question',
            name='date_posted',
            field=models.DateField(default=datetime.datetime(2021, 9, 27, 15, 3, 48, 919829)),
        ),
        migrations.AlterField(
            model_name='student',
            name='dob',
            field=models.DateField(default=datetime.datetime(2021, 9, 27, 15, 3, 48, 912813)),
        ),
    ]
