# Generated by Django 3.2.7 on 2021-09-27 20:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebPage', '0040_auto_20210927_1815'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='Course_Content',
            new_name='Course_Main_Content',
        ),
        migrations.RenameField(
            model_name='course',
            old_name='img',
            new_name='img_cover',
        ),
        migrations.AddField(
            model_name='course',
            name='book_pdf',
            field=models.FileField(null=True, upload_to='Course_Books/'),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='date_posted',
            field=models.DateField(default=datetime.datetime(2021, 9, 27, 22, 15, 16, 497096)),
        ),
        migrations.AlterField(
            model_name='new',
            name='date_posted',
            field=models.DateField(default=datetime.datetime(2021, 9, 27, 22, 15, 16, 499102)),
        ),
        migrations.AlterField(
            model_name='posting',
            name='date_posted',
            field=models.DateField(default=datetime.datetime(2021, 9, 27, 22, 15, 16, 496093)),
        ),
        migrations.AlterField(
            model_name='question',
            name='date_posted',
            field=models.DateField(default=datetime.datetime(2021, 9, 27, 22, 15, 16, 498098)),
        ),
        migrations.AlterField(
            model_name='student',
            name='dob',
            field=models.DateField(default=datetime.datetime(2021, 9, 27, 22, 15, 16, 492082)),
        ),
    ]
