# Generated by Django 3.2.7 on 2021-09-29 14:31

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('WebPage', '0048_auto_20210929_1626'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='date_posted',
            field=models.DateField(default=datetime.datetime(2021, 9, 29, 16, 31, 22, 348465)),
        ),
        migrations.AlterField(
            model_name='new',
            name='date_posted',
            field=models.DateField(default=datetime.datetime(2021, 9, 29, 16, 31, 22, 350470)),
        ),
        migrations.AlterField(
            model_name='posting',
            name='date_posted',
            field=models.DateField(default=datetime.datetime(2021, 9, 29, 16, 31, 22, 347462)),
        ),
        migrations.AlterField(
            model_name='question',
            name='date_posted',
            field=models.DateField(default=datetime.datetime(2021, 9, 29, 16, 31, 22, 349469)),
        ),
        migrations.AlterField(
            model_name='student',
            name='dob',
            field=models.DateField(default=datetime.datetime(2021, 9, 29, 16, 31, 22, 344455)),
        ),
        migrations.CreateModel(
            name='DetailQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Answer', models.TextField()),
                ('Question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WebPage.question')),
            ],
        ),
    ]
